wladder/config/routes.rb
Rails.application.routes.draw do
    root "home#index"
    get 'query', to:'home#show'

end

wladder/app/controllers/home_controller.rb
class HomeController < ApplicationController

    load "#{Rails.root}/lib/ladder.rb"
    load "#{Rails.root}/lib/words4.rb"

    def index
         
    end

    def show
        steps = Array.new
        steps.push params[:start]
        if params[:step1] != ""
            steps.push params[:step1]
        end
        if params[:step2] != ""
            steps.push params[:step2]
        end
        if params[:step3] != ""
            steps.push params[:step3]
        end
        if params[:step4] != ""
            steps.push params[:step4]
        end
        if params[:step5] != ""
            steps.push params[:step5]
        end
        steps.push params[:goal]
        @start = params[:start]
        @goal = params[:goal]
        if (legal steps)
            @result = "Correct, You Win!"
        else
            @result = "Incorrect, You Lose"
        end
    end
end

wladder/app/controllers/ladder.rb
# functions to help with the implementation of the word ladder assignment

# if you place this file in wladder/lib you can use it in your controller
# by loading it:
#   load "#{Rails.root}/lib/ladder.rb"


# only load one dictionary
# load the dictionary of 4-letter words
load "#{Rails.root}/lib/words4.rb"

# load the dictionary of 5-letter words
#load "#{Rails.root}/lib/words5.rb"

# return true if the two strings differ by only one letter
def edit_distance_of_one word1, word2

  return false if word1.length != word2.length || word1.length == 0

  # count the different letters
  difference_count = 0
  word1.split(//).each_with_index do |ch, i|
    difference_count += 1 if word2[i] != ch
  end
  return difference_count == 1
end

# return true if the array steps contains a legal "ladder" progression from
# the first word to the last word
def legal steps

  # if any of the words are not in the dictionary
  steps.each do |word|
    return false if !dictionary.find_index word 
  end
   
  # if consecutive words differ by more than one character
  for i in 0..steps.length-2 do
    return false if !edit_distance_of_one steps[i], steps[i+1]
  end

  # steps forms a legal word ladder
  return true

end

wladder/app/views/home/index.html.erb
<% load "#{Rails.root}/lib/words4.rb"%>
<h1>Brennan's Word Ladder</h1>
<hr>
<div> <p> Fill in each step with a word that differs from the word in the previous step by no more than one character. Once you reach a word that differs from the goal by only one letter, you can stop and leave the remainder of the steps empty. </p> <div>
<br>

<% wordsarray = Array.new %>
<% wordsarray = dictionary %>
<% index = rand(wordsarray.size-1) %>
<% start = wordsarray[index]; wordsarray[index] = nil; wordsarray.compact! %>
<% index = rand(wordsarray.size-1) %>
<% goal = wordsarray[index]; wordsarray[index] = nil; wordsarray.compact! %>

<%= form_tag(query_path, method: "get") do  %>
    <%= hidden_field_tag 'start', start %>
    <%= hidden_field_tag 'goal', goal %>
    <%= label_tag(:start, "Step0: #{start}") %>
    <br>
    <%= label_tag(:query1, "Step1:") %>
    <%= text_field_tag(:step1) %>
    <br>
    <%= label_tag(:query2, "Step2:") %>
    <%= text_field_tag(:step2) %>
    <br>
    <%= label_tag(:query3, "Step3:") %>
    <%= text_field_tag(:step3) %>
    <br>
    <%= label_tag(:query4, "Step4:") %>
    <%= text_field_tag(:step4) %>
    <br>
    <%= label_tag(:query5, "Step5:") %>
    <%= text_field_tag(:step5) %>
    <%= submit_tag("Check Answer") %>
    <br>
    <%= label_tag(:goal, "Goal: #{goal}") %>
<% end %>

wladder/app/views/home/show.html.erb
<!DOCTYPE html>
<%= link_to "Play Again", root_path %>
<html>

<head>
    <link rel="stylesheet" href="/home/ubuntu/465/wladder/app/views/home/style.css">
<style>
h1 {color:blue;}
table, th, td {border: 1px solid red; border-collapse: collapse;}
th, td {padding: 5px;}
</style>
</head>

<body>
<h1> Your Guesses </h1>
<br>
<table>
    <tr>
        <td> <%= "Start:" %> </td>
        <td> <%= params[:start] %> </td>
    </tr>
    <tr>
        <% if params[:step1] != "" %>
        <td> <%= "Step1:" %> </td>
        <td> <%= params[:step1] %> </td>
        <%end%>
    </tr>
    <tr>
        <% if params[:step2] != "" %>
        <td> <%= "Step2:" %> </td>
        <td> <%= params[:step2] %> </td>
        <%end%>
    </tr>
    <tr>
        <% if params[:step3] != "" %>
        <td> <%= "Step3:" %> </td>
        <td> <%= params[:step3] %> </td>
        <%end%>
    </tr>
    <tr>
        <% if params[:step4] != "" %>
        <td> <%= "Step4:" %> </td>
        <td> <%= params[:step4] %> </td>
        <%end%>
    </tr>
    <tr>
        <% if params[:step5] != "" %>
        <td> <%= "Step5:" %> </td>
        <td> <%= params[:step5] %> </td>
        <%end%>
    </tr>
    <tr>
        <td> <%= "End:" %> </td>
        <td> <%= params[:goal] %> </td>
    </tr>
</table>
<h2> <%= @result %> </h2>
</body>
</html>

wladder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wladder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>